<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>

    <Nullable>disable</Nullable>
    <ImplicitUsings>enable>

    <AssemblyName>BossProjectileMultiplier</AssemblyName>
    <RootNamespace>BossProjectileMultiplier</RootNamespace>

    <OutputPath>bin/Release/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TShock" Version="6.1.0" />
    <PackageReference Include="TSAPI" Version="6.1.0" />
  </ItemGroup>

</Project>
